@baseurl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}
# @name create_account
POST {{baseurl}}/accounts
Content-Type: application/json

{
  "name": "Daniel",
  "email": "daniell@gmail.com",
  "password": "123456"
}

###
# @name authenticate

POST {{baseurl}}/sessions
Content-Type: application/json

{
  "email": "daniell@gmail.com",
  "password": "123456"
}

###
# @name create-question

POST {{baseurl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova Pergunta 3",
  "content": "Conteudo da pergunta 3"
}

###
# @name fetch-recent-question

GET  {{baseurl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

